name: Run bing-wallpaper.py and change desktop wallpaper

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    # Runs every day at 8:00 AM
    - cron: '*/2 * * * *'

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      
      # Sets up Python environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      # Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          #pip install ctypes
          pip install re
      
      # Runs your script
      - name: Run bing-wallpaper.py
        run: |
          #cd bing-wallpaper-pictures
          python ./bing-wallpaper.py
      
      # Changes your desktop wallpaper
      - name: Change desktop wallpaper
        run: |
          powershell -command "& {Invoke-WebRequest https://raw.githubusercontent.com/npocmaka/batch.scripts/master/hybrids/.net/c/changeWallpaper.cs -OutFile changeWallpaper.cs; Add-Type -Path changeWallpaper.cs; [Wallpaper.Setter]::SetWallpaper('E:\bing-wallpaper-pictures\bing_wallpaper.jpg', 0)}"
